"""Write src/tgclient/_build.py: version and the app's Telegram API credentials.

Telegram apps ship their api_id/api_hash inside the client (my.telegram.org). They come from
the environment (CI: repository secrets) or, for local builds, from the repo's .env. Never
committed (the file is in .gitignore). The OpenRouter key is NOT baked in: it costs money,
every user adds their own in Settings.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "src" / "tgclient" / "_build.py"


def version() -> str:
    if os.environ.get("TGC_VERSION"):
        return os.environ["TGC_VERSION"]
    try:
        described = subprocess.run(
            ["git", "describe", "--tags", "--always", "--dirty"], cwd=ROOT, check=True,
            capture_output=True, text=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "0.1.0"
    described = described.lstrip("v")
    if re.match(r"\d+\.\d+", described):  # a release tag like v0.2.0 (maybe -3-gabc123)
        return described
    return f"0.1.0.dev+{described}"  # no tags yet: just the commit


def main() -> None:
    from dotenv import load_dotenv

    load_dotenv(ROOT / ".env")  # never overrides variables that are already set
    api_id = os.environ.get("TG_API_ID", "").strip()
    api_hash = os.environ.get("TG_API_HASH", "").strip()
    if not (api_id and api_hash):
        if os.environ.get("TGC_REQUIRE_API") == "1":
            sys.exit("TG_API_ID and TG_API_HASH are required for a release build")
        print("warning: TG_API_ID/TG_API_HASH not set; the build will read them from .env",
              file=sys.stderr)
    lines = [
        '"""Generated by packaging/write_build_info.py. Do not commit."""',
        f"VERSION = {version()!r}",
    ]
    if api_id and api_hash:
        lines += [f"TG_API_ID = {api_id!r}", f"TG_API_HASH = {api_hash!r}"]
    TARGET.write_text("\n".join(lines) + "\n")
    print(f"wrote {TARGET.relative_to(ROOT)} (version {version()})")


if __name__ == "__main__":
    main()
